sudo: false

language: ruby

rvm:
  - 2.4.0

before_install:
  - gem install bundler:1.17.3

cache: bundler
script: bundle exec middleman build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: build/
  on:
    branch: master
